from __future__ import annotations

DEFAULT_NAVER_BUSINESS_ID = "1356779"
DEFAULT_STATION_BRANCH_ID = "18"
DEFAULT_NAVER_ROOM_IDS = ["6556948", "6556938", "7043386"]
DEFAULT_STATION_ROOM_IDS = ["62", "59", "258"]

DEFAULT_STATION_API_BASE = "https://api.admin-stationbyuhc.com"
DEFAULT_NAVER_API_BASE = "https://api-partner.booking.naver.com"

PROVIDER_TARGET_MAX = {
    "NAVER": 4,
    "STATION": 1,
}

APPLY_BLOCKING_VALIDATION_WARN_CODES = {
    "CURRENT_EXCEEDS_MAXIMUM",
    "MAX_DIFFERS_FROM_BASELINE",
    "TARGET_EXCEEDS_PROVIDER_MAX",
}

APPLY_BLOCKING_STATION_WARNING_CODES = {
    "STATION_NO_CALENDAR_ROWS",
    "STATION_NO_PRICE_SET_ID",
}
