(() => {
  const App = (globalThis.App = globalThis.App || {});
  App.ui = App.ui || {};

  function createPanelDom({ style, html, documentRef = document } = {}) {
    const host = documentRef.createElement("div");
    const shadow = host.attachShadow({ mode: "open" });
    shadow.innerHTML = `<style>${style || ""}</style>${html || ""}`;
    documentRef.documentElement.appendChild(host);
    return { host, shadow };
  }

  function collectPanelUi(shadow) {
    const $ = (id) => shadow.getElementById(id);
    return {
      wrap: $("wrap"),
      toggle: $("toggle"),
      backdrop: $("backdrop"),
      panel: $("panel"),
      panelTitle: $("panelTitle"),
      close: $("close"),
      siteLabel: $("siteLabel"),
      flowStepPeriod: $("flowStepPeriod"),
      flowStepLoad: $("flowStepLoad"),
      flowStepReview: $("flowStepReview"),
      flowStepApply: $("flowStepApply"),
      onboardingBox: $("onboardingBox"),
      onboardingSheetItem: $("onboardingSheetItem"),
      onboardingAuthItem: $("onboardingAuthItem"),
      onboardingRangeItem: $("onboardingRangeItem"),
      onboardingTestItem: $("onboardingTestItem"),
      hideOnboardingBtn: $("hideOnboardingBtn"),
      monthLabel: $("monthLabel"),
      prevMonth: $("prevMonth"),
      nextMonth: $("nextMonth"),
      dateGrid: $("dateGrid"),
      pickedText: $("pickedText"),
      presetRange2d: $("presetRange2d"),
      presetRange7d: $("presetRange7d"),
      presetRangeMonth: $("presetRangeMonth"),
      resetDate: $("resetDate"),
      load: $("load"),
      loadAll: $("loadAll"),
      loadSheet: $("loadSheet"),
      applyCorrectionSiteBtn: $("applyCorrectionSiteBtn"),
      applyCorrectionBtn: $("applyCorrectionBtn"),
      downloadCorrectionDiffBtn: $("downloadCorrectionDiffBtn"),
      exportUnknownColorBtn: $("exportUnknownColorBtn"),
      copySite: $("copySite"),
      copySheet: $("copySheet"),
      status: $("status"),
      sumRows: $("sumRows"),
      sumOpen: $("sumOpen"),
      sumClosed: $("sumClosed"),
      sumPeriod: $("sumPeriod"),
      userSyncState: $("userSyncState"),
      userMismatchCount: $("userMismatchCount"),
      userPmsStatus: $("userPmsStatus"),
      userLoadState: $("userLoadState"),
      userOpsHint: $("userOpsHint"),
      siteHead: $("siteHead"),
      siteBody: $("siteBody"),
      sheetHead: $("sheetHead"),
      sheetBody: $("sheetBody"),
      sheetInsightWrap: $("sheetInsightWrap"),
      insightTitle: $("insightTitle"),
      insightHead: $("insightHead"),
      insightBody: $("insightBody"),
      correctionIssueHint: $("correctionIssueHint"),
      syncFeatureSection: $("syncFeatureSection"),
      cfgSpreadsheet: $("cfgSpreadsheet"),
      cfgSheetName: $("cfgSheetName"),
      cfgStartRow: $("cfgStartRow"),
      cfgYear: $("cfgYear"),
      cfgStockMode: $("cfgStockMode"),
      cfgAllowPkgInventoryRows: $("cfgAllowPkgInventoryRows"),
      cfgClientId: $("cfgClientId"),
      cfgClientSecret: $("cfgClientSecret"),
      cfgProviderApply: $("cfgProviderApply"),
      cfgProviderApplyHint: $("cfgProviderApplyHint"),
      cfgAccessToken: $("cfgAccessToken"),
      cfgRefreshToken: $("cfgRefreshToken"),
      cfgPmsPresetKey: $("cfgPmsPresetKey"),
      cfgPmsPropertyNo: $("cfgPmsPropertyNo"),
      cfgPmsBsnsCode: $("cfgPmsBsnsCode"),
      cfgPmsPageId: $("cfgPmsPageId"),
      cfgPmsPageSize: $("cfgPmsPageSize"),
      cfgPmsPresetPreview: $("cfgPmsPresetPreview"),
      cfgPmsPresetApplyBtn: $("cfgPmsPresetApplyBtn"),
      cfgPmsReservationUrl: $("cfgPmsReservationUrl"),
      cfgPmsHarInput: $("cfgPmsHarInput"),
      cfgPmsHarConvertBtn: $("cfgPmsHarConvertBtn"),
      cfgPmsAuthBundle: $("cfgPmsAuthBundle"),
      cfgAuthBundle: $("cfgAuthBundle"),
      captureAuthBundleBtn: $("captureAuthBundleBtn"),
      copyAuthBundleBtn: $("copyAuthBundleBtn"),
      toggleSecretsBtn: $("toggleSecretsBtn"),
      toggleConfig: $("toggleConfig"),
      sheetBox: $("sheetBox"),
      saveSyncCfg: $("saveSyncCfg"),
      toggleOpsSectionBtn: $("toggleOpsSectionBtn"),
      opsSection: $("opsSection"),
      opsPolicySummary: $("opsPolicySummary"),
      opsRetentionSummary: $("opsRetentionSummary"),
      opsEvidenceSummary: $("opsEvidenceSummary"),
      cfgScanMode: $("cfgScanMode"),
      cfgDateAnchorRow: $("cfgDateAnchorRow"),
      cfgManualRanges: $("cfgManualRanges"),
      cfgManualRangeSampleBtn: $("cfgManualRangeSampleBtn"),
      cfgManualRangesPreview: $("cfgManualRangesPreview"),
      syncFeatureToggle: $("syncFeatureToggle"),
      syncApprovalWrap: $("syncApprovalWrap"),
      syncApprovalMismatch: $("syncApprovalMismatch"),
      syncApprovalClosed: $("syncApprovalClosed"),
      syncApprovalPeriod: $("syncApprovalPeriod"),
      syncApprovalCheck: $("syncApprovalCheck"),
      syncBtn: $("syncBtn"),
      syncResultWrap: $("syncResultWrap"),
      syncBlockWrap: $("syncBlockWrap"),
      syncBlockHead: $("syncBlockHead"),
      syncBlockBody: $("syncBlockBody"),
      resTotal: $("resTotal"),
      resSuccess: $("resSuccess"),
      resFail: $("resFail"),
      resClosed: $("resClosed"),
      toggleErrorBtn: $("toggleErrorBtn"),
      errorWrap: $("errorWrap"),
      errorHead: $("errorHead"),
      errorBody: $("errorBody"),
      toggleDebugBtn: $("toggleDebugBtn"),
      debugWrap: $("debugWrap"),
      debugDiag: $("debugDiag"),
      debugLog: $("debugLog"),
      clearRuntimeBtn: $("clearRuntimeBtn"),
      exportTraceJson: $("exportTraceJson"),
      exportTraceCsv: $("exportTraceCsv"),
      exportGoldenSetBtn: $("exportGoldenSetBtn"),
      correctionBadge: $("correctionBadge"),
      verifyNote: $("verifyNote"),
      verifyIssueWrap: $("verifyIssueWrap"),
      verifyIssueHead: $("verifyIssueHead"),
      verifyIssueBody: $("verifyIssueBody")
    };
  }

  App.ui.panelDom = {
    createPanelDom,
    collectPanelUi
  };
})();
