export type BridgeErrorCode =
  | "BRIDGE_UNAVAILABLE"
  | "BRIDGE_DEGRADED"
  | "BRIDGE_AUTH_REQUIRED"
  | "BRIDGE_AUTH_INVALID"
  | "BRIDGE_RATE_LIMITED"
  | "BRIDGE_PAYLOAD_TOO_LARGE"
  | "BRIDGE_SCHEMA_INVALID"
  | "BRIDGE_TIMEOUT"
  | "BRIDGE_PORT_BIND_FAILED"
  | "FIXTURE_FALLBACK_ACTIVE"
  | "UPSTREAM_AUTH_EXPIRED"
  | "WRITE_BLOCKED_REAUTH_REQUIRED"
  | "NO_ACTIVE_TAB"
  | "SESSION_MISSING"
  | "AUTH_CAPTURE_FAILED"
  | "AUTH_RESTORE_FAILED"
  | "DOM_EXTRACT_FAILED"
  | "PROVIDER_FETCH_FAILED"
  | "UNSUPPORTED_PROVIDER"
  | "UNKNOWN_ERROR";

export interface BridgeFailure {
  code: BridgeErrorCode;
  message: string;
  retryable: boolean;
  detail?: string;
}
