import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("desktopBridge", {
  ping: () => ipcRenderer.invoke("desktop:ping"),
  getContext: () => ipcRenderer.invoke("desktop:get-context"),
  loadBindingDecisions: (request: unknown) => ipcRenderer.invoke("desktop:load-binding-decisions", request),
  saveBindingDecision: (request: unknown) => ipcRenderer.invoke("desktop:save-binding-decision", request),
  deleteBindingDecision: (request: unknown) => ipcRenderer.invoke("desktop:delete-binding-decision", request),
  loadRecommendationTraces: (request: unknown) => ipcRenderer.invoke("desktop:load-recommendation-traces", request),
  saveRecommendationTrace: (request: unknown) => ipcRenderer.invoke("desktop:save-recommendation-trace", request),
  loadManualScanAnchor: (request: unknown) => ipcRenderer.invoke("desktop:load-manual-scan-anchor", request),
  saveManualScanAnchor: (request: unknown) => ipcRenderer.invoke("desktop:save-manual-scan-anchor", request),
  deleteManualScanAnchor: (request: unknown) => ipcRenderer.invoke("desktop:delete-manual-scan-anchor", request),
  fetchSheetSnapshot: (request: unknown) => ipcRenderer.invoke("desktop:fetch-sheet-snapshot", request),
  fetchLiveReadBundle: (request: unknown) => ipcRenderer.invoke("desktop:fetch-live-read-bundle", request),
  indexWorkspaceSearch: (request: unknown) => ipcRenderer.invoke("desktop:index-workspace-search", request),
  queryWorkspaceSearch: (request: unknown) => ipcRenderer.invoke("desktop:query-workspace-search", request),
  buildOperatorExport: (request: unknown) => ipcRenderer.invoke("desktop:build-operator-export", request),
  exportOperatorHandoff: (request: unknown) => ipcRenderer.invoke("desktop:export-operator-handoff", request),
  repeatOperatorHandoff: (request: unknown) => ipcRenderer.invoke("desktop:repeat-operator-handoff", request),
  updateOperatorHandoffStatus: (request: unknown) => ipcRenderer.invoke("desktop:update-operator-handoff-status", request),
  fetchProviderRows: (request: unknown) => ipcRenderer.invoke("desktop:fetch-provider-rows", request),
  fetchProviderReservations: (request: unknown) => ipcRenderer.invoke("desktop:fetch-provider-reservations", request),
  fetchWingsLiveContract: (request: unknown) => ipcRenderer.invoke("desktop:fetch-wings-live-contract", request),
  openWingsLogin: () => ipcRenderer.invoke("desktop:open-wings-login"),
  captureWingsSession: () => ipcRenderer.invoke("desktop:capture-wings-session"),
  getBridgeMeta: () => ipcRenderer.invoke("desktop:get-bridge-meta"),
  getBridgeRuntime: () => ipcRenderer.invoke("desktop:get-bridge-runtime"),
  getBridgeSummary: (provider?: unknown) => ipcRenderer.invoke("desktop:get-bridge-summary", provider)
});
